# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=1.0.0
group=io.drahlek.smartfeedingtroughs
java_version=25

# Common
minecraft_version=26.1.2
minecraft_version_min=26.1
minecraft_version_max=26.2
mod_name=Smart Feeding Troughs
mod_author=Drahlek
mod_id=smartfeedingtroughs
license=MIT
credits=
description=Automate animal feeding with a smart trough that feeds nearby mobs and triggers feeding automatically.
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1-1
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=
parchment_version=

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.147.0+26.1.2
fabric_loader_version=0.18.5
loom_version=1.15-SNAPSHOT

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.1.2.30-beta
neoforge_loader_version_range=[11,)

# Dirigo
dirigo_min_version=1.1.0
dirigo_max_version=2.0.0

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.configuration-cache=false
